# Publication half of the release process for this repository. This runs on
# pushes to `main` and will detect a magical string in commit messages. When
# found a tag will be created, pushed, and then everything is published.

name: Publish Artifacts
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  create_tag:
    name: Publish artifacts of build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
    - uses: ./.github/actions/publish-release
      with:
        cargo_token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
